package com.datajpa;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * Auto-generated by: org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name = "item_site")
@IdClass(com.datajpa.ItemSiteId.class)
public class ItemSite {

	@Id @ManyToOne private Item item;
	@Id @ManyToOne private Site site;

	/**
	 * Instantiates a new item site.
	 */
	public ItemSite() {}

	public Item getItem() {
		return item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public Site getSite() {
		return site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

}
